#
# This is a generated file.
#

api.version=v1.0
entity.class.name=liferay.jwt.custom.token.dto.v1_0.JWTTokenResponse
osgi.jaxrs.application.select=(osgi.jaxrs.name=LiferayJwtCustomToken)
osgi.jaxrs.resource=true